common: &default_settings
  adapter: postgresql
  hostname: localhost
  port: 5432
  pool: 5
  reaping_frequency: 10
  timeout: 5000
  encoding: utf-8
development:
  <<: *default_settings
  database: auctionet_dev
production:
  <<: *default_settings
  database: auctionet_prod
test:
  <<: *default_settings
  database: auctionet_test
